spring:
  application:
    name: core-common-reference-master-data
    version: 1.0.0
    description: Reference Master Data Application
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:https://app-firefly-config-server.dev.soon.es/}"